# Generated by Django 4.2.5 on 2023-09-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.CharField(max_length=300),
        ),
    ]
